/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Codes.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Objects;
import javax.swing.JOptionPane;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class SignUp extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public SignUp() {
        initComponents();
        conn = DBconnection.Connect();
    }
    
    
    public static boolean isValidSriLankaPhoneNumber(String phoneNumber) {
        
        String regex = "^(0(7\\d{8}|1\\d{8}))$"; // Mobile (07xxxxxxx) or Landline (01xxxxxxx)
        
        if (phoneNumber != null && phoneNumber.matches(regex)) {
            return true;
        } else {
            // Show error message if phone number is not in the format
            JOptionPane.showMessageDialog(null, "Invalid phone number! Please enter a valid Sri Lankan phone number.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    
    public static boolean isValidAge(String age) {
        if (age == null || age.isEmpty()) {
            // Show error message if age is null or empty
            JOptionPane.showMessageDialog(null, "Age cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return false; 
        }
        if (!age.matches("\\d+")) {
            // Show error message if age is not only integer
            JOptionPane.showMessageDialog(null, "Age must be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
            return false; 
        }
        if (Integer.parseInt(age)<0 ||Integer.parseInt(age)>120){
            // Show error message if age is not in the range of 0-120
            JOptionPane.showMessageDialog(null, "Age must be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
            return false; 
        }
        
        return true;
    }
    
    
    
     private static final String regex = "^[a-zA-Z0-9._%+-]+@gmail\\.com$";

     public static boolean isValidGmail(String email) {
        if (email == null || email.isEmpty()) {
            // Show error message if email is null or empty
            JOptionPane.showMessageDialog(null, "Email cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (!Pattern.matches(regex, email)) {
            // Show error message if email does not have "@gmail.com"
            JOptionPane.showMessageDialog(null, "Invalid Gmail address! Please enter a valid Gmail address.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PhoneNumberBox = new javax.swing.JTextField();
        EmailBox = new javax.swing.JTextField();
        NameBox = new javax.swing.JTextField();
        AddressBox = new javax.swing.JTextField();
        ShowPasswordCheck = new javax.swing.JCheckBox();
        PasswordBox = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        AgeBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GenderComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel4.setText("Phone Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sign Up to Care Point");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 710, 50));
        jPanel1.add(PhoneNumberBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 410, -1));

        EmailBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailBoxActionPerformed(evt);
            }
        });
        jPanel1.add(EmailBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 410, -1));
        jPanel1.add(NameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 410, -1));
        jPanel1.add(AddressBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 410, -1));

        ShowPasswordCheck.setText("Show Password");
        ShowPasswordCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordCheckActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPasswordCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        PasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordBoxActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 410, -1));

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        jLabel7.setText("Age");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        jPanel1.add(AgeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, -1));

        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(GenderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hh1.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 430, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPasswordCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordCheckActionPerformed
        if(ShowPasswordCheck.isSelected()){
            PasswordBox.setEchoChar((char)0);
        }
        else{
            PasswordBox.setEchoChar(('*'));
        } 
    }//GEN-LAST:event_ShowPasswordCheckActionPerformed

    private void PasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EmailBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int num;
        
        String name;
        int age;
        String email;
        String password;
        String gender;
        String phonenumber;
        String address;
        
        name = NameBox.getText();
        age = Integer.parseInt(AgeBox.getText());
        email = EmailBox.getText();
        password = PasswordBox.getText();
        gender = GenderComboBox.getSelectedItem().toString();
        phonenumber = PhoneNumberBox.getText();
        address = AddressBox.getText();
        
        String agestring = String.valueOf(age);
        
        if(isValidGmail(email) && isValidSriLankaPhoneNumber(phonenumber) && isValidAge(agestring)){
            
        
        
        if (Objects.equals(name, "")) {
            num = 1;
        } else {
            num = 2;
        }
        
        try {
            if(num == 1){
                JOptionPane.showMessageDialog(null, "Please fill the form correctly!");
            }else{
                
                String sql = "INSERT INTO patient(Name, Age, Gender, Phone_Number, Email, Password, Address) VALUES ('"+name+"', '"+age+"','"+gender+"','"+phonenumber+"','"+email+"','"+password+"','"+address+"')";
                pst = conn.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Inserted");

                Login l = new Login();
                l.show();
                dispose();
                
                /*
                MainMenu mainmenu = new MainMenu();
                mainmenu.show();
                dispose();
                */
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        patienttableload();
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressBox;
    private javax.swing.JTextField AgeBox;
    private javax.swing.JTextField EmailBox;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JTextField NameBox;
    private javax.swing.JPasswordField PasswordBox;
    private javax.swing.JTextField PhoneNumberBox;
    private javax.swing.JCheckBox ShowPasswordCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void patienttableload() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
